name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - run: flutter --version

      # Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Get Flutter dependencies
      - run: flutter pub get

      # Add secrets to android/secrets.properties
      - name: Create secrets.properties in android folder
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > android/secrets.properties

      # Build APK
      - run: flutter build apk --release --split-per-abi

      # Build IPA without code signing
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload

      # Push artifacts to GitHub Release
      - name: Push to Releases
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            build/app/outputs/apk/release/*
            build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Optional: Upload APK to GitHub Actions artifacts
      # - name: Upload APK as Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk
